# Copyright 2025-2026 NGG. All Rights Reserved.
"""Generate a per-BP conversion brief (playbook Phase 3.5 pre-flight, automated).

Combines `_order.json` (tiers, cycles, per-function engine-only / project split) with the
per-asset extracted record (parent, components, variables, function signatures) into a
ready-to-act brief: what to port, in what order, what blocks each function, and what to
likely skip. Pure Python over JSON — no editor.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import typemap
import codegen
import config

# Function-name signals for the playbook "don't port" heuristic.
_SKIP_HINT = re.compile(r"(?i)\b(debug|draw|log|visuali[sz]e|telemetry)")


def _short(path: str) -> str:
    return path.split(".", 1)[0].rstrip("/").rsplit("/", 1)[-1]


def render_brief(name: str, record: dict, order_asset: dict, cycles: list[list[str]], index: dict) -> str:
    a = record.get("asset", {})
    kind = a.get("asset_kind") or "?"
    system = a.get("system") or "?"
    tier = order_asset.get("tier", "?")
    parent = a.get("parent_class") or "(unknown)"
    detail = order_asset.get("dependencies_detail", {})
    by_graph = detail.get("by_graph", {})

    lines = [
        "---", "type: brief", "tags: [conversion-brief, generated]", "---", "",
        f"# Conversion Brief: {name}", "",
        f"- Kind: **{kind}** | System: **{system}** | Tier: **{tier}**",
        f"- Parent: `{parent}`",
        "",
        "> Generated by `py Plugins\\UnrealNGGMCP\\Tools\\bp-extract brief`. Methodology: [[BP_TO_CPP_PLAYBOOK]].",
        "",
    ]

    cluster = next((c for c in cycles if name in c), None)
    if cluster:
        others = ", ".join(f"[[{n}]]" for n in cluster if n != name)
        lines += ["## Cycle",
                  f"Part of a dependency cycle with {others}. Break the seam (interface / "
                  "forward-decl / soft ref) or convert the cluster together.", ""]

    comps = record.get("components") or []
    if comps:
        lines += ["## Components", ""]
        lines += [f"- `{c.get('name')}` : `{c.get('class')}`" for c in comps]
        lines.append("")

    variables = record.get("variables") or []
    if variables:
        lines += ["## Variables", ""]
        for v in variables:
            cpp = typemap.map_var_type(v.get("type", ""), v.get("type_object"), index)
            lines.append(f"- `{v.get('name')}` : `{cpp}`")
        lines.append("")

    # Functions split.
    engine_only, project_dep, skip = [], [], []
    for fname, g in sorted(by_graph.items()):
        if g.get("kind") != "function":
            continue
        if _SKIP_HINT.search(fname):
            skip.append((fname, g.get("project", [])))
        elif g.get("engine_only"):
            engine_only.append(fname)
        else:
            project_dep.append((fname, g.get("project", [])))

    lines += ["## Functions — migration order", ""]
    lines += ["### Port first (engine-only)", ""]
    lines += [f"- [ ] `{f}`" for f in engine_only] or ["_none_"]
    lines += ["", "### Needs project deps (port after the deps)", ""]
    if project_dep:
        for f, deps in project_dep:
            links = ", ".join(f"[[{_short(d)}]]" for d in deps) or "project types"
            lines.append(f"- [ ] `{f}` → {links}")
    else:
        lines.append("_none_")
    lines += ["", "### Likely skip (debug-only name — verify: plugin dep? no C++ caller?)", ""]
    if skip:
        for f, deps in skip:
            links = ", ".join(f"[[{_short(d)}]]" for d in deps)
            lines.append(f"- `{f}`" + (f" → {links}" if links else ""))
    else:
        lines.append("_none_")

    external = order_asset.get("external") or []
    if external:
        lines += ["", "## Unresolved / external references", "",
                  "_Not in the extracted inventory — verify manually._", ""]
        lines += [f"- `{e}`" for e in external]

    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass

    parser = argparse.ArgumentParser(
        prog="bp-extract brief",
        description="Generate per-BP conversion briefs (pre-flight matrix) from extracted JSON + _order.json.")
    parser.add_argument("name", nargs="?", default=None, help="Asset name (omit for all).")
    parser.add_argument("--out", type=Path, default=None, help="Extracted-JSON dir (default: <vault>/_extracted).")
    parser.add_argument("--briefs", type=Path, default=None, help="Output dir for briefs (default: <vault>/_briefs).")
    config.add_common_args(parser)
    args = parser.parse_args(argv)

    cfg = config.resolve(args)
    config.configure(cfg)
    if config.maybe_print_config(cfg, args):
        return 0
    out_dir = args.out or cfg.out_dir
    briefs_dir = args.briefs or cfg.briefs_dir

    order_file = out_dir / "_order.json"
    if not order_file.exists():
        print(f"{order_file} not found. Run `bp-extract order` first.", file=sys.stderr)
        return 1
    order = json.loads(order_file.read_text(encoding="utf-8"))
    order_assets = order.get("assets", {})
    cycles = order.get("cycles", [])

    records = codegen._load_records(out_dir)
    index = codegen.build_index(records)
    by_name = {r["asset"]["name"]: r for r in records if r.get("asset", {}).get("name")}
    # order_assets is keyed by object path; remap to name.
    order_by_name = {_short(p): v for p, v in order_assets.items()}

    targets = [args.name] if args.name else sorted(by_name)
    written = 0
    for name in targets:
        rec = by_name.get(name)
        if not rec:
            print(f"  no record for '{name}'", file=sys.stderr)
            continue
        oa = order_by_name.get(name, {})
        system = rec["asset"].get("system") or "Misc"
        dest = briefs_dir / system / f"{name}.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(render_brief(name, rec, oa, cycles, index), encoding="utf-8")
        written += 1

    print(f"Wrote {written} brief(s) to {briefs_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
